# Generated by Django 2.2.24 on 2023-11-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_sso_login', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='ssologinextradata',
        #     name='type_document',
        #     field=models.TextField(choices=[('rut', 'Rut'), ('passport', 'Passport'), ('dni', 'DNI')], help_text='Seleccione el tipo de documento', max_length=10, verbose_name='Tipo de documento'),
        # ),
    ]
