# Generated by Django 2.2.24 on 2024-03-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_sso_login', '0003_auto_20231128_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssologinextradata',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ssologinextradata',
            name='type_document',
            field=models.CharField(choices=[('rut', 'Rut'), ('passport', 'Passport'), ('dni', 'DNI')], help_text='Select document type', max_length=10, verbose_name='Document type'),
        ),
    ]
