# Generated by Django 2.2.24 on 2024-03-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eol_sso_login', '0004_auto_20240313_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssologinextradata',
            name='is_completed',
        ),
    ]
