# Generated by Django 2.2.24 on 2024-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_sso_login', '0005_remove_ssologinextradata_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssologinextradata',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
