# Generated by Django 2.2.24 on 2024-03-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eol_sso_login', '0006_ssologinextradata_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssologinextradata',
            name='is_completed',
        ),
    ]
